example_app/example_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
]

example_app/polls/urls.py
# file to store the url of our app

from django.urls import path, include
from . import views

# Variable with the main name of our url
app_name = 'polls'

"""
# urls settings to class generic views
urlpatterns = [
    #example: polls/
    path('', views.IndexView.as_view(), name='index'),
    
    #example: polls/1
    path('<int:pk>/detail', views.NumberQuestionView.as_view(), name='number_question'),

    #example: polls/1/results
    path('<int:pk>/results', views.ResultView.as_view(), name='question_results'),

    #example: polls/1/votes
    path('<int:id_question>/votes', views.votes, name='question_votes'),
]
"""
# urls settings to functions views
urlpatterns = [
    #example: polls/
    path('', views.index, name='index'),
    
    #example: polls/1
    path('<int:id_question>/detail', views.number_question, name='number_question'),

    #example: polls/1/results
    path('<int:id_question>/results', views.results, name='question_results'),

    #example: polls/1/votes
    path('<int:id_question>/votes', views.votes, name='question_votes'),
]

example_app/login/models.py
from django.db import models

# Create your models here.

example_app/polls/models.py
from django.db import models
from django.utils import timezone
import datetime

class Question(models.Model):

    # Attributes of this class are the columns of the a table
    # Id column it isn't necessary wrote because Django sets it automatically
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.question_text
    
    def was_recent_question(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    
    # For foreign key, we need to specify the class wherein the primary key is.
    # "on_delete=models.CASCADE" is used to delete another answers that doesn't match with key.
    question =models.ForeignKey(Question, on_delete=models.CASCADE, related_name='question_choices')
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

example_app/login/views.py
from django.shortcuts import render

# Create your views here.

example_app/polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic

from .models import Question, Choice

"""
# Generic Views or Class Generic Views.

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    # method to run query of our models
    def get_queryset(self):
        # order_by function allows us to get records, if we aggregate "-" before the key, it'll 
        # sort the list descending.  
        return Question.objects.order_by('-pub_date')[:5]

class NumberQuestionView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'
    

# using the inherit concept to avoid DRY
class ResultView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'
"""


# Function Views
def index(request):

    # In this variable, we get all questions from model object Question. 
    latest_question_list = Question.objects.all()

    # We returt the template from the templates/polls/index.html and we indicate the variables we need to use. 
    return render(request, 'polls/index.html', {
        "latest_question_list":latest_question_list
    })


def number_question(request, id_question):
    
    # We're using the get_object_or_404 function to manage the error http when the consult is not effective.
    question_1 = get_object_or_404(Question, pk=id_question)
    return render(request, "polls/detail.html", {
        "question_1":question_1
    })


def results(request, id_question):
    # We're using the get_object_or_404 function to manage the error http when the consult is not effective.
    question_1 = get_object_or_404(Question, pk=id_question)
    return render(request, 'polls/results.html', {
        "question_1" : question_1
    })

def votes(request, id_question):
    
    # firstly, we must call a object of Question model
    question_1 = get_object_or_404(Question, pk=id_question)

    # secondly, we manage the flow of the logic through try-except
    try:
        # Here, we use the function request.POST[] to get the data from the forms
        # according to the choice selected.
        # The POST[] dictionary call the key 'choice', related with the label name in the form.
        selected_choice = question_1.question_choices.get(pk=request.POST['choice'])
    except(KeyError, Choice.DoesNotExist):
        # If the user doesn't select some item, we render the same "detail" view but we add the
        # error_message variable to the view.
        return render(request, 'polls/detail.html', {
            "question_1":question_1,
            "error_message":"You must select some anwser. Please, select one item."
        })
    else:
        # If the user selected one item and the request.POST[] found the id, we can start the counter
        # in the attribute "votes" from Choice Model and save the result into the model (database).
        selected_choice.votes += 1
        selected_choice.save()
        
        # we'll redirect to the user to 'question_results' view through the function 
        # reverse(), this one is the same code "% url %" used in the templates, but 
        # now it's wroten in python 
        
        return HttpResponseRedirect(reverse('polls:question_results', args=(question_1.id,)))

example_app/polls/templates/polls/detail.html
<form action="{% url 'polls:question_votes' question_1.id %}" method="post">
{% csrf_token %}
<fieldset>
    <legend>
        <h1>
            {{ question_1.question_text }}
        </h1>
    </legend>
    {% if error_message %}
        <p>
            <strong>
                {{ error_message }}
            </strong>
        </p>
    {% endif %}
    {% for c in question_1.question_choices.all %}
        <input 
            type="radio"
            name="choice"
            id="choice{{ forloop.counter }}"
            value="{{c.id}}"
        >
        <label for="choice{{ forloop.counter }}">
            {{ c.choice_text }}
        </label>
        <br>
    {% endfor %}
</fieldset>
<br>    
<input type="submit" value="Let's Vote">

</form>


{% comment %}
<h1> {{ question_1.question_text }} </h1>

<ol>
    {% for c in question_1.question_choices.all %}
        <li>
            {{ c.choice_text }}
        </li>
    {% endfor %}
</ol>
{% endcomment %}

example_app/polls/templates/polls/index.html
<h1>Home Page for Polls</h1>

{% if latest_question_list %}
    <ol>
    {% for q in latest_question_list %}
        <li>
            <a href="{% url 'polls:number_question' q.id %}">
                {{q.question_text}}
            </a>
        </li>
    {% endfor %}    
    </ol>
{% else %}
    <p>No polls are available</p>
{% endif %}

example_app/polls/templates/polls/results.html
<h1>Results of the Polls for {{ question_1.question_text }}</h1>

<ul>
    {% for c in question_1.question_choices.all %}
        <li>
            <!-- we use pluralize function to add the "s" letter if the votes is greater than 1 -->
            {{ c.choice_text }} ----| {{ c.votes }} vote{{ c.votes | pluralize:'y,ies' }}
        </li>
    {% endfor %}
</ul>

<a href="{% url 'polls:number_question' question_1.id %}"> Do you want to vote again? </a>
<br>
<a href=" {% url 'polls:index' %}">I want to return to home</a>